### ISSUE TITLE
Generate pdf without css 

### ISSUE THREAD

**Issue by melthibault95** [TakeoO/zend-pdf#1]
Hey,

I'm working on a Zend Framework 3 project and I'm using your tool to generate PDF files but when I use it, it gives me that message : "Exit with code 1 due to network error: ContentNotFoundError".
I have my PDF file but without CSS.
Do you have some ideas ?

**Comment by TakeoO** [comment]
Yes, you have to have full path to your assets eg: https://mysite.com/css/main.css and if you develop on local machine or vagrant or any other kind of dev envirnoment you have to setup hosts file to point to local machine.
So if you are developing using vagrant with *unix system and have test domain https://test.dev, you have to add a line into your /etc/hosts file: 

`127.0.0.1 test.dev`
